[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist/"

[context.production.environment]
  PNPM_VERSION = "5.4.0"

[[plugins]]
  package = "@netlify/plugin-corepack"