const emojis = {
  ["(口罩)"]: "kouzhao",
  ["(吓出汗了)"]: "lenghan",
  ["(白眼)"]: "baiyan",
  ["(调皮)"]: "tiaopi",
  ["(破防)"]: "fanu",
  ["(朕乏了)"]: "kun",
  ["(笑不活了)"]: "leiku",
  ["(开心)"]: "kaixin",
  ["(微笑)"]: "weixiao",
  ["(疑问)"]: "yiwen",
  ["(吐舌头)"]: "shetou",
  ["(得意儿的笑)"]: "daxiao",
  ["(直呼内行)"]: "jingya",
  ["(吓到朕了)"]: "jingxia",
  ["(感冒)"]: "ganmao",
  ["(太tm失望了)"]: "shiwang",
  ["(没意思)"]: "wuliao",
  ["(蓝瘦香菇)"]: "juezui",
  ["(急了急了)"]: "jiyan",
  ["(发呆)"]: "dai",
  ["(泪目)"]: "liulei",
  ["(我晕)"]: "yun",
  ["(爱了爱了)"]: "se",
  ["(天使)"]: "tianshi",
  ["(你懂的)"]: "huaixiao",
  ["(呆住了)"]: "fadai",
  ["(吐了yue)"]: "tu",
  ["(魔王)"]: "mowang",
  ["(困觉了)"]: "shuijue",
  ["(哭死)"]: "ku",
}
Object.keys(emojis).forEach(key => {
  emojis[key] = `https://fuyouplus.oss-cn-beijing.aliyuncs.com/emoji/${emojis[key]}.png`
})
export default emojis
